/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { Receipt, DollarSign, Wallet, Percent, MessageSquareDot } from 'lucide-react';
import { Sale, AdCampaign } from '../types';

interface KPICardsProps {
  sales: Sale[];
  campaigns: AdCampaign[];
  activeCountry: string;
  countriesConfig: Record<string, { currency: string; rate: number }>;
}

export default function KPICards({ sales, campaigns, activeCountry, countriesConfig }: KPICardsProps) {
  // Calculations
  const totalSalesCount = sales.length;
  const totalRevenueUsd = sales.reduce((acc, s) => acc + s.amountUsd, 0);
  const totalSpendUsd = campaigns.reduce((acc, c) => acc + c.spend, 0);
  const globalRoas = totalSpendUsd > 0 ? (totalRevenueUsd / totalSpendUsd) : 0;
  
  // Lead-to-Sale Conversion rate (WhatsApp conversion funnel)
  // Approximate total leads generated by campaigns
  const totalAdConversions = campaigns.reduce((acc, c) => acc + c.conversions, 0);
  const conversionRate = totalAdConversions > 0 
    ? Math.min(100, (totalSalesCount / totalAdConversions) * 100) 
    : 0;

  // Average Ticket
  const ticketPromedioUsd = totalSalesCount > 0 ? totalRevenueUsd / totalSalesCount : 0;

  // Local currency indicator
  const getLocalTicketString = () => {
    if (activeCountry !== 'All' && countriesConfig[activeCountry]) {
      const rateInfo = countriesConfig[activeCountry];
      const localAmount = Math.round(ticketPromedioUsd * rateInfo.rate);
      return `${localAmount.toLocaleString()} ${rateInfo.currency}`;
    }
    return null;
  };

  const localTicket = getLocalTicketString();

  // Color logic for ROAS
  const getRoasColor = (roas: number) => {
    if (roas >= 3.0) return 'text-emerald-400 border-emerald-500/20 bg-emerald-500/5';
    if (roas >= 2.0) return 'text-sky-400 border-sky-500/20 bg-sky-500/5';
    if (roas >= 1.0) return 'text-amber-400 border-amber-500/20 bg-amber-500/5';
    return 'text-rose-400 border-rose-500/20 bg-rose-500/5';
  };

  const getRoasBadgeLabel = (roas: number) => {
    if (roas >= 3.0) return 'Excelente (Escalar)';
    if (roas >= 2.0) return 'Sólido (Mantener)';
    if (roas >= 1.0) return 'Marginal (Optimizar)';
    return 'Crítico (Pausar)';
  };

  const cardStyle = "bg-[#11131c] border border-[#1f2335] rounded-xl p-5 flex flex-col justify-between shadow-lg relative overflow-hidden";

  return (
    <div id="kpi-cards-grid" className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4 mb-6">
      {/* Sales Count Card */}
      <div className={cardStyle}>
        <div className="flex items-center justify-between mb-3">
          <span className="text-xs font-mono text-gray-400 uppercase tracking-wider">Entes (Ventas)</span>
          <div className="p-2 bg-blue-500/10 text-[#3b82f6] rounded-lg">
            <Receipt className="w-4 h-4" />
          </div>
        </div>
        <div>
          <h3 className="text-2xl font-display font-bold text-white leading-none mb-1">
            {totalSalesCount.toLocaleString()}
          </h3>
          <p className="text-[10px] text-gray-500 font-mono">Conversiones reales WhatsApp</p>
        </div>
      </div>

      {/* Revenue Card */}
      <div className={cardStyle}>
        <div className="flex items-center justify-between mb-3">
          <span className="text-xs font-mono text-gray-400 uppercase tracking-wider">Ingreso Total</span>
          <div className="p-2 bg-emerald-500/10 text-emerald-400 rounded-lg">
            <DollarSign className="w-4 h-4" />
          </div>
        </div>
        <div>
          <h3 className="text-2xl font-display font-bold text-emerald-400 leading-none mb-1">
            ${totalRevenueUsd.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
          </h3>
          <p className="text-[10px] text-gray-500 font-mono">Facturación en dólares (USD)</p>
        </div>
      </div>

      {/* Spend Card */}
      <div className={cardStyle}>
        <div className="flex items-center justify-between mb-3">
          <span className="text-xs font-mono text-gray-400 uppercase tracking-wider font-semibold">Gasto Meta Ads</span>
          <div className="p-2 bg-purple-500/10 text-purple-400 rounded-lg">
            <Wallet className="w-4 h-4" />
          </div>
        </div>
        <div>
          <h3 className="text-2xl font-display font-bold text-purple-300 leading-none mb-1">
            ${totalSpendUsd.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
          </h3>
          <p className="text-[10px] text-gray-500 font-mono">Presupuesto absorbido</p>
        </div>
      </div>

      {/* ROAS Card */}
      <div className={`${cardStyle} border-l-2 ${globalRoas > 0 ? getRoasColor(globalRoas).split(' ')[1] : ''}`}>
        <div className="flex items-center justify-between mb-2">
          <span className="text-xs font-mono text-gray-400 uppercase tracking-wider">ROAS General</span>
          <div className="p-2 bg-yellow-500/10 text-yellow-400 rounded-lg">
            <Percent className="w-4 h-4" />
          </div>
        </div>
        <div>
          <h3 className={`text-2xl font-display font-bold leading-none mb-1 ${globalRoas > 0 ? getRoasColor(globalRoas).split(' ')[0] : 'text-gray-400'}`}>
            {globalRoas > 0 ? `${globalRoas.toFixed(2)}x` : 'N/A'}
          </h3>
          <span className={`inline-block px-1.5 py-0.5 rounded text-[9px] font-mono border ${globalRoas > 0 ? getRoasColor(globalRoas) : 'text-gray-400 border-gray-500/20 bg-gray-500/5'}`}>
            {globalRoas > 0 ? getRoasBadgeLabel(globalRoas) : 'Sin Gasto'}
          </span>
        </div>
      </div>

      {/* Lead to Sale Funnel Card */}
      <div className={cardStyle}>
        <div className="flex items-center justify-between mb-3">
          <span className="text-xs font-mono text-gray-400 uppercase tracking-wider">Ticket Promedio</span>
          <div className="p-2 bg-cyan-500/10 text-cyan-400 rounded-lg">
            <MessageSquareDot className="w-4 h-4" />
          </div>
        </div>
        <div>
          <h3 className="text-2xl font-display font-bold text-white leading-none mb-1">
            ${ticketPromedioUsd.toFixed(1)} <span className="text-xs text-gray-400">USD</span>
          </h3>
          <p className="text-[10px] text-[#06b6d4] font-mono leading-tight">
            {localTicket ? `≈ ${localTicket}` : 'Precios mixtos LATAM'}
          </p>
        </div>
      </div>
    </div>
  );
}
